// Generated by CoffeeScript 2.3.2
(function() {
  var Discord, Statics;

  Discord = require('discord.js');

  Statics = require('./statics');

  exports.error = function(chan, cont, title) {
    var emb, msg;
    msg = null;
    emb = new Discord.RichEmbed().setDescription(cont).setColor(Statics.COLORS.error);
    if (title) {
      emb.setTitle(title);
    }
    return chan.send('', emb);
  };

  exports.default = function(chan, cont, title, color) {
    var emb, msg;
    msg = null;
    emb = new Discord.RichEmbed().setDescription(cont).setColor(color ? color : Statics.COLORS.main);
    if (title) {
      emb.setTitle(title);
    }
    return chan.send('', emb);
  };

  exports.invalidInput = function(chan, cmd) {
    return exports.error(chan, `Please enter \`help ${cmd}\` to get information how to use this command.`, "INVALID INPUT");
  };

}).call(this);
